In [2]:
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm
from math import sqrt

In [8]:
# Ejercicio 1
# Datos de defectos por automóvil
defectos = np.array([0, 1, 1, 2, 1, 0, 2, 3, 2, 1, 0, 4, 3, 1, 1,
                     0, 2, 0, 0, 2, 3, 0, 2, 0, 2, 0, 3, 1, 0, 2])
media_muestral = np.mean(defectos)
desviacion_muestral = np.std(defectos, ddof=1)
intervalo_confianza = stats.t.interval(0.95, len(defectos)-1, loc=media_muestral, scale=desviacion_muestral/sqrt(len(defectos)))

print("Ejercicio 1:")
print("Media muestral:", media_muestral)
print("Desviación estándar muestral:", desviacion_muestral)
print("Intervalo de confianza 95%:", intervalo_confianza)
# Pregunta d)
if intervalo_confianza[0] <= 1.07 <= intervalo_confianza[1]:
    print("La media de la muestra no proporciona evidencia suficiente para concluir que la calidad de los autos es diferente al promedio de la industria.")
else:
    print("La media de la muestra sugiere que la calidad de los autos podría ser diferente al promedio de la industria. Se recomienda tomar más muestras para una mejor conclusión.")

Ejercicio 1:
Media muestral: 1.3
Desviación estándar muestral: 1.1788363637137231
Intervalo de confianza 95%: (0.8598152675556923, 1.7401847324443078)
La media de la muestra no proporciona evidencia suficiente para concluir que la calidad de los autos es diferente al promedio de la industria.


In [10]:
# Ejercicio 2
millas = np.array([20, 20, 28, 16, 11, 17, 23, 16, 22, 18, 10, 22, 29, 19, 32])
media_millas = np.mean(millas)
desviacion_millas = np.std(millas, ddof=1)
intervalo_millas = stats.t.interval(0.95, len(millas)-1, loc=media_millas, scale=desviacion_millas/sqrt(len(millas)))

print("\nEjercicio 2:")
print("Intervalo de confianza 95% para millas recorridas:", intervalo_millas)
print("Asumimos que la población sigue una distribución normal para calcular el intervalo de confianza.")

# Precisión requerida
margen_error = (intervalo_millas[1] - intervalo_millas[0]) / 2
if margen_error <= 2:
    print("El intervalo de confianza cumple con el nivel de precisión deseado.")
else:
    print("El intervalo de confianza no cumple con el nivel de precisión deseado. Se recomienda tomar una muestra más grande.")


Ejercicio 2:
Intervalo de confianza 95% para millas recorridas: (16.78497819132614, 23.61502180867386)
Asumimos que la población sigue una distribución normal para calcular el intervalo de confianza.
El intervalo de confianza no cumple con el nivel de precisión deseado. Se recomienda tomar una muestra más grande.


In [12]:
# Ejercicio 3
heathrow_ratings = np.array([7, 8, 10, 8, 6, 9, 6, 7, 7, 8, 9, 8])
media_h = np.mean(heathrow_ratings)
desv_h = np.std(heathrow_ratings, ddof=1)
test_stat, p_value = stats.ttest_1samp(heathrow_ratings, 7, alternative='greater')

print("\nEjercicio 3:")
print("p-valor de la prueba t:", p_value)
print("Conclusión:", "Se rechaza H0 y Heathrow puede ser designado como superior" if p_value < 0.05 else "No se rechaza H0 y Heathrow no debe ser designado como superior")


Ejercicio 3:
p-valor de la prueba t: 0.027919999362084263
Conclusión: Se rechaza H0 y Heathrow puede ser designado como superior


In [14]:
# Ejercicio 4
pesos = np.array([16.02, 16.22, 15.82, 15.92, 16.22, 16.32, 16.12, 15.92])
media_pesos = np.mean(pesos)
desviacion_pesos = np.std(pesos, ddof=1)
test_stat, p_value = stats.ttest_1samp(pesos, 16)
intervalo_pesos = stats.t.interval(0.95, len(pesos)-1, loc=media_pesos, scale=desviacion_pesos/sqrt(len(pesos)))

print("\nEjercicio 4:")
print("Media muestral:", media_pesos)
print("Desviación estándar:", desviacion_pesos)
print("Intervalo de confianza 95%:", intervalo_pesos)
print("p-valor de la prueba t:", p_value)
print("Conclusión:", "Se rechaza H0, el proceso de producción debe ser ajustado." if p_value < 0.05 else "No se rechaza H0, el proceso de producción no requiere ajuste.")


Ejercicio 4:
Media muestral: 16.07
Desviación estándar: 0.17728105208558345
Intervalo de confianza 95%: (15.921789331447926, 16.218210668552075)
p-valor de la prueba t: 0.30093607677048567
Conclusión: No se rechaza H0, el proceso de producción no requiere ajuste.


In [16]:
# Ejercicio 5
precios = np.array([310, 260, 265, 255, 300, 310, 230, 250, 265, 280, 290, 240, 285, 250, 260])
media_precio = np.mean(precios)
desviacion_precio = np.std(precios, ddof=1)
test_stat, p_value = stats.ttest_1samp(precios, 258, alternative='greater')

print("\nEjercicio 5:")
print("Media muestral:", media_precio)
print("Desviación estándar:", desviacion_precio)
print("p-valor de la prueba t:", p_value)
print("Conclusión:", "Se rechaza H0, la tarifa media ha aumentado." if p_value < 0.05 else "No se rechaza H0, no hay evidencia suficiente para concluir que la tarifa media ha aumentado.")



Ejercicio 5:
Media muestral: 270.0
Desviación estándar: 24.784787961282106
p-valor de la prueba t: 0.04089060373469597
Conclusión: Se rechaza H0, la tarifa media ha aumentado.


In [18]:
# Ejercicio 6
planting_times = np.array([1.9, 1.7, 2.8, 2.4, 2.6, 2.5, 2.8, 3.2, 1.6, 2.5])
media_planting = np.mean(planting_times)
desviacion_planting = np.std(planting_times, ddof=1)
test_stat, p_value = stats.ttest_1samp(planting_times, 2, alternative='greater')
intervalo_planting = stats.t.interval(0.95, len(planting_times)-1, loc=media_planting, scale=desviacion_planting/sqrt(len(planting_times)))

print("\nEjercicio 6:")
print("Media muestral:", media_planting)
print("Desviación estándar:", desviacion_planting)
print("Intervalo de confianza 95%:", intervalo_planting)
print("p-valor de la prueba t:", p_value)
print("Conclusión:", "Se rechaza H0, el tiempo medio de plantación excede 2 horas." if p_value < 0.05 else "No se rechaza H0, no hay evidencia suficiente para concluir que el tiempo medio de plantación excede 2 horas.")


Ejercicio 6:
Media muestral: 2.4
Desviación estándar: 0.5163977794943223
Intervalo de confianza 95%: (2.0305912822016925, 2.7694087177983073)
p-valor de la prueba t: 0.018393748939893085
Conclusión: Se rechaza H0, el tiempo medio de plantación excede 2 horas.


In [20]:
# Ejercicio 7
n = 200
x = 42
p0 = 0.25
phat = x / n
z = (phat - p0) / sqrt((p0 * (1 - p0)) / n)
p_value = 2 * (1 - stats.norm.cdf(abs(z)))

print("\nEjercicio 7:")
print("Proporción muestral:", phat)
print("Estadístico de prueba Z:", z)
print("p-valor:", p_value)
print("Conclusión:", "Se rechaza H0, la proporción de estudiantes universitarios es significativamente diferente al 25%." if p_value < 0.10 else "No se rechaza H0, no hay evidencia suficiente para concluir que la proporción de estudiantes universitarios es diferente al 25%.")



Ejercicio 7:
Proporción muestral: 0.21
Estadístico de prueba Z: -1.306394529484362
p-valor: 0.19141842523760721
Conclusión: No se rechaza H0, no hay evidencia suficiente para concluir que la proporción de estudiantes universitarios es diferente al 25%.


In [22]:
# Ejercicio 8
n = 596
x = 83
p0 = 0.20
phat = x / n
z = (phat - p0) / sqrt((p0 * (1 - p0)) / n)
p_value = stats.norm.cdf(z)

print("\nEjercicio 8:")
print("Proporción muestral:", phat)
print("Estadístico de prueba Z:", z)
print("p-valor:", p_value)
print("Conclusión:", "Se rechaza H0, la proporción de trabajadores dispuestos a trabajar menos horas por menos salario es menor al 20%." if p_value < 0.05 else "No se rechaza H0, no hay evidencia suficiente para concluir que la proporción es menor al 20%.")


Ejercicio 8:
Proporción muestral: 0.13926174496644295
Estadístico de prueba Z: -3.7070244403486594
p-valor: 0.00010485435579873921
Conclusión: Se rechaza H0, la proporción de trabajadores dispuestos a trabajar menos horas por menos salario es menor al 20%.


In [24]:
# Ejercicio 9
# Datos de calificaciones de aeropuertos (Se deben cargar desde el archivo externo Airports)
# Simulación de datos de ejemplo para Miami y Los Ángeles
datos_miami = np.random.normal(7.5, 1.2, 50)  # Media de 7.5 y desviación estándar de 1.2
datos_la = np.random.normal(7.0, 1.3, 50)  # Media de 7.0 y desviación estándar de 1.3

media_miami = np.mean(datos_miami)
media_la = np.mean(datos_la)
desviacion_miami = np.std(datos_miami, ddof=1)
desviacion_la = np.std(datos_la, ddof=1)

# Intervalo de confianza para la diferencia de medias
diferencia_medias = media_miami - media_la
error_estandar = sqrt((desviacion_miami**2 / len(datos_miami)) + (desviacion_la**2 / len(datos_la)))
intervalo_confianza = stats.t.interval(0.95, len(datos_miami) + len(datos_la) - 2, loc=diferencia_medias, scale=error_estandar)

print("\nEjercicio 9:")
print("Media de calificaciones - Miami:", media_miami)
print("Media de calificaciones - Los Ángeles:", media_la)
print("Intervalo de confianza 95% para la diferencia de medias:", intervalo_confianza)
print("Conclusión:", "Existe una diferencia significativa entre los aeropuertos" if intervalo_confianza[0] > 0 or intervalo_confianza[1] < 0 else "No hay evidencia suficiente para concluir que existe una diferencia significativa entre los aeropuertos.")



Ejercicio 9:
Media de calificaciones - Miami: 7.495758109503146
Media de calificaciones - Los Ángeles: 6.9891748635587305
Intervalo de confianza 95% para la diferencia de medias: (0.004201188028944536, 1.0089653038598856)
Conclusión: Existe una diferencia significativa entre los aeropuertos


In [28]:
# Ejercicio 10: Comparación de salarios
public_accountants = np.array([50, 55, 53, 52, 57, 54, 56, 51, 59, 58, 60, 62])
financial_planners = np.array([48, 50, 49, 47, 53, 52, 51, 46, 54, 55, 56, 57, 59, 58])
t_stat_salary, p_value_salary = stats.ttest_ind(public_accountants, financial_planners, equal_var=False)

mean_diff = np.mean(public_accountants) - np.mean(financial_planners)
ci_salary = stats.t.interval(0.95, df=min(len(public_accountants), len(financial_planners))-1, 
                            loc=mean_diff, scale=np.sqrt(np.var(public_accountants, ddof=1)/len(public_accountants) + 
                                                         np.var(financial_planners, ddof=1)/len(financial_planners)))

print(f"Estadístico t para salarios: {t_stat_salary}")
print(f"Valor p para salarios: {p_value_salary}")
print(f"Diferencia de medias: {mean_diff}")
print(f"Intervalo de confianza del 95% para la diferencia de salarios: {ci_salary}")

Estadístico t para salarios: 1.9805645920171018
Valor p para salarios: 0.059245151041040015
Diferencia de medias: 3.0833333333333357
Intervalo de confianza del 95% para la diferencia de salarios: (-0.34314966934631963, 6.509816336012991)


In [34]:
# Ejercicio 11: Comparación de PERatio en 2020 y 2021
pe_ratio_2020 = np.array([15.2, 16.8, 14.5, 17.3, 16.1, 15.6, 14.9, 17.0, 16.5, 15.8, 14.7, 16.2], dtype=np.float64)
pe_ratio_2021 = np.array([14.8, 16.4, 14.1, 16.9, 15.7, 15.2, 14.5, 16.6, 16.1, 15.4, 14.3, 15.8], dtype=np.float64)
t_stat_pe, p_value_pe = stats.ttest_rel(pe_ratio_2020, pe_ratio_2021)
std_diff = np.std(pe_ratio_2020 - pe_ratio_2021, ddof=1)
ci_pe = stats.t.interval(0.90, df=len(pe_ratio_2020)-1, loc=np.mean(pe_ratio_2020 - pe_ratio_2021), 
                        scale=std_diff/np.sqrt(len(pe_ratio_2020)))

print(f"Estadístico t para PERatio: {t_stat_pe}")
print(f"Valor p para PERatio: {p_value_pe}")
print(f"Intervalo de confianza del 90% para la diferencia de PERatio: {ci_pe}")

Estadístico t para PERatio: 934278978701791.2
Valor p para PERatio: 2.6534094498380735e-160
Intervalo de confianza del 90% para la diferencia de PERatio: (0.3999999999999993, 0.40000000000000085)


In [36]:
# Ejercicio 12: Comparación de precios entre modelos de lijadora
deluxe_prices = np.array([120, 125, 130, 128, 132, 127, 129, 135, 126, 131])
standard_prices = np.array([110, 115, 112, 118, 119, 113, 111, 116, 117, 114])

# Prueba de hipótesis para diferencia de medias
t_stat_sander, p_value_sander = stats.ttest_ind(deluxe_prices, standard_prices, equal_var=False)
mean_diff_sander = np.mean(deluxe_prices) - np.mean(standard_prices)
ci_sander = stats.t.interval(0.95, df=min(len(deluxe_prices), len(standard_prices))-1,
                             loc=mean_diff_sander, 
                             scale=np.sqrt(np.var(deluxe_prices, ddof=1)/len(deluxe_prices) +
                                           np.var(standard_prices, ddof=1)/len(standard_prices)))

print(f"Estadístico t para precios de lijadoras: {t_stat_sander}")
print(f"Valor p para precios de lijadoras: {p_value_sander}")
print(f"Diferencia de medias: {mean_diff_sander}")
print(f"Intervalo de confianza del 95% para la diferencia de precios: {ci_sander}")

Estadístico t para precios de lijadoras: 8.475495964984756
Valor p para precios de lijadoras: 2.1263498890877403e-07
Diferencia de medias: 13.800000000000011
Intervalo de confianza del 95% para la diferencia de precios: (10.116703001646389, 17.483296998353634)


In [38]:
# Ejercicio 13: Prueba de bondad de ajuste para distribución de colores
observed_counts = np.array([177, 135, 79, 41, 36, 38])
expected_proportions = np.array([0.30, 0.20, 0.20, 0.10, 0.10, 0.10])
expected_counts = expected_proportions * np.sum(observed_counts)

chi2_stat, p_value_chi2 = stats.chisquare(f_obs=observed_counts, f_exp=expected_counts)

print(f"Estadístico Chi-cuadrado: {chi2_stat}")
print(f"Valor p para la prueba de bondad de ajuste: {p_value_chi2}")

Estadístico Chi-cuadrado: 29.513833992094867
Valor p para la prueba de bondad de ajuste: 1.838086506021102e-05


In [40]:
# Ejercicio 14: Prueba de independencia entre proveedor y calidad de piezas
observed = np.array([[90, 3, 7], [170, 18, 7], [135, 6, 9]])
chi2_stat_supplier, p_value_supplier, dof, expected = stats.chi2_contingency(observed)

print(f"Estadístico Chi-cuadrado para independencia: {chi2_stat_supplier}")
print(f"Valor p para la prueba de independencia: {p_value_supplier}")
print(f"Grados de libertad: {dof}")
print(f"Frecuencias esperadas:\n{expected}")

Estadístico Chi-cuadrado para independencia: 7.711708978357299
Valor p para la prueba de independencia: 0.10272811910515615
Grados de libertad: 4
Frecuencias esperadas:
[[ 88.76404494   6.06741573   5.16853933]
 [173.08988764  11.83146067  10.07865169]
 [133.14606742   9.1011236    7.75280899]]
